### PR TITLE
Updated the name in readme.

### PR DESCRIPTION
**Pull request by Mihir-Bhasin**
[=] Updated the readme name

### CODE REVIEW

**Comment by Kulsk** [comment]
hi, [=] fix a few gramma errors in API documentation
as mentioned in https://github.com/alibaba/xquic/blob/main/CONTRIBUTING.md#commit-messages

**Comment by RuiqiZhou** [comment]
Thanks for your contribution, but would you mind changing the commit messages to
`[=] Updated the readme name`
as mentioned in https://github.com/alibaba/xquic/blob/main/CONTRIBUTING.md#commit-messages

**Comment by Mihir-Bhasin** [comment]
Done.

**Comment by RuiqiZhou** [comment]
> Done.

To change the commit message, you should rebase and then force push.

https://docs.github.com/en/get-started/using-git/about-git-rebase#commands-available-while-rebasing
> reword
The reword command is similar to pick, but after you use it, the rebase process will pause and give you a chance to alter the commit message. Any changes made by the commit are not affected.

and the PR can only be merged after you have signed the CLA.

**Comment by Mihir-Bhasin** [comment]
I have singed the CLA

**Review by RuiqiZhou — CHANGES_REQUESTED** [review]
change the commit messages to `[=] Updated the readme name` and then force push

**Comment by Mihir-Bhasin** [comment]
can u tell me how to do it in the git GUI I didn't quite get that

**Comment by RuiqiZhou** [comment]
> https://docs.github.com/en/get-started/using-git/about-git-rebase#commands-available-while-rebasing

I think it would be easier to use the command line, see https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line

**Comment by RuiqiZhou** [comment]
Hi, #46 has solved this problem, so I will close this PR.

**Pull request closed without merging**
